name: Build and Deploy EC2

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
      - run: npm ci --force
      
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
      #- run: npm run build --force

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          
          remote_path: server/
          remote_host: ec2-18-117-128-5.us-east-2.compute.amazonaws.com
          remote_user: Andrew
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
